fix: handle functools.partial callbacks in _make_callback_repr
When using Django Ninja or similar frameworks that wrap view functions
using functools.partial, the `_make_callback_repr` function crashes with:

    AttributeError: 'functools.partial' object has no attribute '__qualname__'

This happens because functools.partial objects don't have __qualname__
or __module__ attributes directly - they are on the wrapped function.

The fix adds a check for functools.partial and accesses the underlying
function via callback.func to get the qualname and module.

Fixes crash when checking URLconfs that include Django Ninja API routes.